apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdstechday-backend-nodejs
  namespace: backend
  labels:
    app: mdstechday-backend-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdstechday-backend-nodejs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mdstechday-backend-nodejs
    spec:
      containers:
      - image: brentley/ecsdemo-nodejs:latest
        imagePullPolicy: Always
        name: mdstechday-backend-nodejs
        ports:
        - containerPort: 3000
          protocol: TCP
